[tool]
  [tool.bumpversion]
    allow_dirty = true
    current_version = "0.3.11"

    [[tool.bumpversion.files]]
      filename = "pyproject.toml"
      replace = "current_version = \"{new_version}\""
      search = "current_version = \"{current_version}\""

    [[tool.bumpversion.files]]
      filename = "src/tag_commit/__init__.py"
      replace = "__version__ = \"{new_version}\""
      search = "__version__ = \"{current_version}\""
