[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[project]
  name = "dycw-tag-commit"
  requires-python = ">= 3.14"

[dependency-groups]
  dev = ["dycw-utilities[test]", "rich"]
